### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by gyulakiraly** [percosys/git-controlhub#5]
[Enter steps to reproduce:]

1. Deselected all items from workspace
2. Atom Error popped up

**Atom**: 1.21.1 ia32
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [git-controlhub](https://github.com/alexisaperez/git-controlhub) package 0.4.0

### Stack Trace

Uncaught TypeError: Path must be a string. Received undefined

```
At path.js:7

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:468:7)
    at Object.isMerging (/packages/git-controlhub/lib/git.coffee:124:31)
    at GitControlhubView.module.exports.GitControlhubView.showSelectedFiles (/packages/git-controlhub/lib/git-controlhub-view.coffee:112:72)
    at FileView.module.exports.FileView.showSelected (/packages/git-controlhub/lib/views/file-view.coffee:75:17)
    at FileView.module.exports.FileView.selectAll (/packages/git-controlhub/lib/views/file-view.coffee:129:6)
    at /packages/git-control/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLDivElement.dispatch (/packages/git-control/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/git-control/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -9:50.6.0 intentions:highlight (input.hidden-input)
     -9:50.4.0 core:save (input.hidden-input)
     -9:26.2.0 intentions:highlight (input.hidden-input)
     -9:25.9.0 core:save (input.hidden-input)
  4x -7:08.2.0 intentions:highlight (input.hidden-input)
     -7:07.5.0 find-and-replace:show (input.hidden-input)
     -6:17 editor:newline (input.hidden-input)
     -6:12.1.0 intentions:highlight (input.hidden-input)
     -6:12 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-typescript 11.0.10 
autocomplete-modules 1.7.3 
autocomplete-paths 2.12.1 
busy-signal 1.4.3 
git-controlhub 0.4.0 
intentions 1.1.5 
language-postcss 1.3.1 
line-ending-converter 1.3.2 
linter 2.2.0 
linter-ui-default 1.6.10 
webbox-color 0.5.9 
```

**Comment by jpoles1** [comment]
Same here.
