### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received undefined UBUNTU LINUX

### ISSUE THREAD

**Issue by wesferr** [percosys/git-controlhub#6]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Ubuntu 16.04.3
**Thrown From**: [git-controlhub](https://github.com/alexisaperez/git-controlhub) package 0.4.0
**User**: root

### Stack Trace

Uncaught TypeError: Path must be a string. Received undefined

```
At path.js:7

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)
    at Object.isMerging (/packages/git-controlhub/lib/git.coffee:124:31)
    at GitControlhubView.module.exports.GitControlhubView.showSelectedFiles (/packages/git-controlhub/lib/git-controlhub-view.coffee:112:72)
    at FileView.module.exports.FileView.showSelected (/packages/git-controlhub/lib/views/file-view.coffee:75:17)
    at FileView.module.exports.FileView.selectAll (/packages/git-controlhub/lib/views/file-view.coffee:129:6)
    at /packages/git-log/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLDivElement.dispatch (/packages/git-log/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/git-log/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
  2x -8:19.9.0 git-gui:toggle (atom-pane.pane)
     -6:23.2.0 git-diff:toggle-diff-list (ul.list-inline.tab-bar.inset-panel)
     -6:16.4.0 github:toggle-git-tab (select.github-BranchMenuView-item.github-BranchMenuView-select.input-select)
     -6:06.1.0 open-on-github:file-on-master (div.github-StagingView.staged-changes-focused)
     -6:02.6.0 open-on-github:blame (div.github-StagingView.staged-changes-focused)
     -5:57.6.0 open-on-github:repository (div.github-StagingView.staged-changes-focused)
     -5:28.8.0 command-palette:toggle (atom-pane.pane)
  5x -5:26.3.0 core:move-down (input.hidden-input)
  2x -5:24.9.0 core:move-up (input.hidden-input)
     -5:24.3.0 core:confirm (input.hidden-input)
     -5:24.2.0 open-on-github:history (atom-pane.pane)
     -4:11.3.0 core:page-down (input.hidden-input)
     -4:11.3.0 core:confirm (input.hidden-input)
     -3:17.3.0 git-control:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:05.6.0 core:confirm (input.hidden-input)
     -1:04.2.0 git-controlhub:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
git-controlhub 0.4.0 
git-log 0.4.1 
```

**Comment by danieleliberti** [comment]
Same bug on OSX High Sierra

**Comment by irvnriir** [comment]
same on win10, happens when removing checkmarks and fist 2 times on clicking check all.

**Comment by mkschulze** [comment]
any update on this? happens here as well on High Sierra
