### ISSUE TITLE
Uncaught Error: Repository has been destroyed

### ISSUE THREAD

**Issue by kdjsystem** [percosys/git-controlhub#9]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.13.6
**Thrown From**: [git-controlhub](https://github.com/alexisaperez/git-controlhub) package 0.4.0

### Stack Trace

Uncaught Error: Repository has been destroyed

```
At /Applications/Atom.app/Contents/Resources/app/src/git-repository.js:537

Error: Repository has been destroyed
    at GitRepository.getRepo (/Applications/Atom.app/Contents/Resources/app/src/git-repository.js:537:19)
    at GitRepository.getShortHead (/Applications/Atom.app/Contents/Resources/app/src/git-repository.js:237:23)
    at Object.getLocalBranch (/packages/git-controlhub/lib/git.coffee:118:17)
    at GitControlhubView.module.exports.GitControlhubView.loadBranches (/packages/git-controlhub/lib/git-controlhub-view.coffee:100:29)
    at GitControlhubView.module.exports.GitControlhubView.update (/packages/git-controlhub/lib/git-controlhub-view.coffee:70:8)
    at Object.updateViews (/packages/git-controlhub/lib/git-controlhub.coffee:44:9)
    at /packages/git-controlhub/lib/git-controlhub.coffee:17:57
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at Workspace.didActivatePaneContainer (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:430:26)
    at Dock.subscriptions.CompositeDisposable.paneContainer.onDidActivatePane (/Applications/Atom.app/Contents/Resources/app/src/dock.js:62:20)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at PaneContainer.didActivatePane (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:265:24)
    at Pane.activate (/Applications/Atom.app/Contents/Resources/app/src/pane.js:1018:46)
    at Pane.focus (/Applications/Atom.app/Contents/Resources/app/src/pane.js:401:23)
    at HTMLElement.handleFocus (/app.asar/src/pane-element.js:41:20)
```

### Commands

```
     -3:47.9.0 tree-view:remove (div.header.list-item.project-root-header)
  3x -3:36.9.0 tree-view:remove-project-folder (span.name.icon.icon-file-directory)
     -3:17 application:add-project-folder (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:05.6.0 core:paste (input.input-text.native-key-bindings)
```

### Non-Core Packages

```
git-clone 0.2.0 
git-control 0.9.0 
git-controlhub 0.4.0 
git-plus 8.1.0 
php-server 0.8.0 
```

**Comment by kdjsystem** [comment]
commit
